# Generated by Django 3.1.7 on 2021-03-30 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoastsRoastsModel',
            new_name='RBModel',
        ),
    ]
