# Generated by Django 3.1.7 on 2021-03-30 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0002_auto_20210330_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbmodel',
            name='privatesecret_key',
        ),
    ]
